apiVersion: v1
kind: Service
metadata:
  name: blueprint-service
  namespace: blueprint-ns
spec:
  selector:
    app: blueprint
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
